site_name: IoT-Software
repo_name: 'itmo-ict-faculty'
repo_url: 'https://github.com/itmo-ict-faculty/iot-software'
theme:
  name: material
  # palette:
  #   - scheme: default
  #     toggle:
  #       icon: material/weather-sunny
  #       name: Switch to dark mode
  #   - scheme: slate
  #     toggle:
  #       icon: material/weather-night
  #       name: Switch to light mode
#  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
#    - navigation.tabs
#    - navigation.tabs.sticky
    - toc.follow
    - navigation.top
plugins:
  - search
nav:
  - Introduction: "index.md"
  - Education:
    - Courses: "education/courses.md"
    - Labs: "education/labs.md"
    - Lecture: "education/lecture.md"
    - Additional materials: "education/additional_materials.md"
    # - Exam: "education/exam.md"
  # - Student case: 
  #   - ITMO 2022/2023: "student_case/itmo2022_2023/itmo2022_2023.md"